name: Build LaTeX document
# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]

jobs:
  build_and_upload_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.aux
          compiler: bibtex
          args:
      - name: pdflatex thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
